-- MySQL Script generated by MySQL Workbench
-- Tue Feb  4 17:45:42 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ecommerce
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ecommerce
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ecommerce` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `ecommerce` ;

-- -----------------------------------------------------
-- Table `ecommerce`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`endereco` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador único do endereço',
  `cep` INT NULL DEFAULT NULL COMMENT 'Código de Endereçamento Postal (CEP)',
  `rua` VARCHAR(255) NULL DEFAULT NULL COMMENT 'Nome da rua',
  `complemento` VARCHAR(255) NULL DEFAULT NULL COMMENT 'Informações complementares do endereço',
  `logradouro` VARCHAR(100) NULL DEFAULT NULL COMMENT 'Tipo de logradouro (Avenida, Rua, etc.)',
  `bairro` VARCHAR(100) NULL DEFAULT NULL COMMENT 'Nome do bairro',
  `cidade` VARCHAR(100) NULL DEFAULT NULL COMMENT 'Nome da cidade',
  `estado` VARCHAR(100) NULL DEFAULT NULL COMMENT 'Nome do estado',
  `numero` INT NULL DEFAULT NULL COMMENT 'Número do endereço',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 31
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecommerce`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`cliente` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador único do cliente',
  `nome` VARCHAR(100) NULL DEFAULT NULL COMMENT 'Nome completo do cliente',
  `cpf` VARCHAR(14) NULL DEFAULT NULL COMMENT 'Cadastro de Pessoa Física (CPF) do cliente',
  `email` VARCHAR(100) NULL DEFAULT NULL COMMENT 'Endereço de e-mail do cliente',
  `senha` VARCHAR(100) NULL DEFAULT NULL COMMENT 'Senha de acesso do cliente',
  `telefone` VARCHAR(15) NULL DEFAULT NULL COMMENT 'Número de telefone do cliente',
  `dataNascimento` DATE NULL DEFAULT NULL COMMENT 'Data de nascimento do cliente',
  `nacionalidade` VARCHAR(50) NULL DEFAULT NULL COMMENT 'País de origem do cliente',
  `genero` VARCHAR(10) NULL DEFAULT NULL COMMENT 'Gênero do cliente',
  `endereco_id` INT NULL DEFAULT NULL COMMENT 'Referência ao endereço do cliente',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cpf` (`cpf` ASC) VISIBLE,
  UNIQUE INDEX `email` (`email` ASC) VISIBLE,
  INDEX `endereco_id` (`endereco_id` ASC) VISIBLE,
  CONSTRAINT `cliente_ibfk_1`
    FOREIGN KEY (`endereco_id`)
    REFERENCES `ecommerce`.`endereco` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 31
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecommerce`.`vendedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`vendedor` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador único do vendedor',
  `nome` VARCHAR(100) NULL DEFAULT NULL COMMENT 'Nome completo do vendedor',
  `cpf` VARCHAR(14) NULL DEFAULT NULL COMMENT 'Cadastro de Pessoa Física (CPF) do vendedor',
  `cnpj` VARCHAR(18) NULL DEFAULT NULL COMMENT 'Cadastro Nacional de Pessoa Jurídica (CNPJ), caso aplicável',
  `email` VARCHAR(100) NULL DEFAULT NULL COMMENT 'Endereço de e-mail do vendedor',
  `senha` VARCHAR(100) NULL DEFAULT NULL COMMENT 'Senha de acesso do vendedor',
  `telefone` VARCHAR(15) NULL DEFAULT NULL COMMENT 'Número de telefone do vendedor',
  `dataNascimento` DATE NULL DEFAULT NULL COMMENT 'Data de nascimento do vendedor',
  `nacionalidade` VARCHAR(50) NULL DEFAULT NULL COMMENT 'País de origem do vendedor',
  `genero` VARCHAR(10) NULL DEFAULT NULL COMMENT 'Gênero do vendedor',
  `endereco_id` INT NULL DEFAULT NULL COMMENT 'Referência ao endereço do vendedor',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cpf` (`cpf` ASC) VISIBLE,
  UNIQUE INDEX `cnpj` (`cnpj` ASC) VISIBLE,
  UNIQUE INDEX `email` (`email` ASC) VISIBLE,
  INDEX `endereco_id` (`endereco_id` ASC) VISIBLE,
  CONSTRAINT `vendedor_ibfk_1`
    FOREIGN KEY (`endereco_id`)
    REFERENCES `ecommerce`.`endereco` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 41
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecommerce`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`produto` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador único do produto',
  `nome` VARCHAR(100) NULL DEFAULT NULL COMMENT 'Nome do produto',
  `descricao` TEXT NULL DEFAULT NULL COMMENT 'Descrição detalhada do produto',
  `valor_atual` DOUBLE NULL DEFAULT NULL COMMENT 'Preço unitário do produto',
  `estoque` INT NULL DEFAULT NULL COMMENT 'Quantidade disponível em estoque',
  `custo_atual` DOUBLE NULL DEFAULT NULL,
  `vendedor_id` INT NULL DEFAULT NULL COMMENT 'Referência ao vendedor do produto',
  PRIMARY KEY (`id`),
  INDEX `vendedor_id` (`vendedor_id` ASC) VISIBLE,
  CONSTRAINT `produto_ibfk_1`
    FOREIGN KEY (`vendedor_id`)
    REFERENCES `ecommerce`.`vendedor` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 51
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecommerce`.`avaliacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`avaliacao` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador único da avaliação',
  `nota` INT NULL DEFAULT NULL COMMENT 'Nota atribuída ao produto (1 a 5)',
  `comentario` TEXT NULL DEFAULT NULL COMMENT 'Comentário do cliente sobre o produto',
  `data` DATE NULL DEFAULT NULL COMMENT 'Data em que a avaliação foi realizada',
  `cliente_id` INT NULL DEFAULT NULL COMMENT 'Referência ao cliente que fez a avaliação',
  `produto_id` INT NULL DEFAULT NULL COMMENT 'Referência ao produto avaliado',
  PRIMARY KEY (`id`),
  INDEX `cliente_id` (`cliente_id` ASC) VISIBLE,
  INDEX `produto_id` (`produto_id` ASC) VISIBLE,
  CONSTRAINT `avaliacao_ibfk_1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `ecommerce`.`cliente` (`id`)
    ON DELETE SET NULL,
  CONSTRAINT `avaliacao_ibfk_2`
    FOREIGN KEY (`produto_id`)
    REFERENCES `ecommerce`.`produto` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 52
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecommerce`.`carrinho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`carrinho` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador único do carrinho',
  `cliente_id` INT NOT NULL COMMENT 'Referência ao cliente que criou o carrinho',
  `data_criacao` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Data e hora de criação do carrinho',
  PRIMARY KEY (`id`),
  INDEX `fk_carrinho_cliente_idx` (`cliente_id` ASC) VISIBLE,
  CONSTRAINT `fk_carrinho_cliente`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `ecommerce`.`cliente` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecommerce`.`itenscarrinho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`itenscarrinho` (
  `carrinho_id` INT NOT NULL COMMENT 'Referência ao carrinho',
  `produto_id` INT NOT NULL COMMENT 'Referência ao produto',
  `quantidade` INT NOT NULL COMMENT 'Quantidade do produto no carrinho',
  `preco_unitario` DOUBLE NOT NULL COMMENT 'Preço do produto no momento da adição',
  PRIMARY KEY (`carrinho_id`, `produto_id`),
  INDEX `fk_itensCarrinho_produto_idx` (`produto_id` ASC) VISIBLE,
  CONSTRAINT `fk_itensCarrinho_carrinho`
    FOREIGN KEY (`carrinho_id`)
    REFERENCES `ecommerce`.`carrinho` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_itensCarrinho_produto`
    FOREIGN KEY (`produto_id`)
    REFERENCES `ecommerce`.`produto` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecommerce`.`venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`venda` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador único do carrinho',
  `data_hora` DATETIME NULL DEFAULT NULL COMMENT 'Data em que o pedido foi realizado',
  `total_pago` DOUBLE NULL DEFAULT NULL COMMENT 'Valor total dos itens no carrinho',
  `tipoPagamento` VARCHAR(45) NULL DEFAULT NULL COMMENT 'Código do tipo de pagamento escolhido',
  `pagamento_efetuado` TINYINT NULL DEFAULT NULL,
  `cliente_id` INT NULL DEFAULT NULL COMMENT 'Referência ao cliente que criou o carrinho',
  PRIMARY KEY (`id`),
  INDEX `cliente_id` (`cliente_id` ASC) VISIBLE,
  CONSTRAINT `carrinho_ibfk_1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `ecommerce`.`cliente` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 34
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecommerce`.`itensvenda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`itensvenda` (
  `produto_id` INT NOT NULL COMMENT 'Referência ao produto',
  `venda_id` INT NOT NULL COMMENT 'Referência à venda',
  `quantidade` INT NULL DEFAULT NULL COMMENT 'Quantidade de produto na venda',
  `preco_praticado` DOUBLE NULL DEFAULT NULL COMMENT 'Preço do produto no momento da venda',
  PRIMARY KEY (`produto_id`, `venda_id`),
  INDEX `fk_produto_has_venda_venda1_idx` (`venda_id` ASC) VISIBLE,
  INDEX `fk_produto_has_venda_produto1_idx` (`produto_id` ASC) VISIBLE,
  CONSTRAINT `fk_produto_has_venda_produto1`
    FOREIGN KEY (`produto_id`)
    REFERENCES `ecommerce`.`produto` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_produto_has_venda_venda1`
    FOREIGN KEY (`venda_id`)
    REFERENCES `ecommerce`.`venda` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
